## Association Rule Mining Using Apriori Algorithm

In [18]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [19]:
data = pd.read_csv('../data/groceries.csv')
data.head()

,1,2,3,4,5,6,7,8,9
0,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN
1,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN
2,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,pip fruit,yogurt,cream cheese,meat spreads,NaN,NaN,NaN,NaN,NaN
4,other vegetables,whole milk,condensed milk,long life bakery product,NaN,NaN,NaN,NaN,NaN

In [20]:
baskets_sets = data.stack().str.get_dummies().groupby(level=0).sum()
baskets_sets.head()

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,bags,baking powder,bathroom cleaner,beef,berries,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [21]:
baskets_sets_bool = baskets_sets.astype(bool)
apriori(baskets_sets_bool, min_support=0.02, use_colnames=True)

      support                                         itemsets
0    0.028155                                       (UHT-milk)
1    0.054369                                           (beef)
2    0.032039                                        (berries)
3    0.027508                                      (beverages)
4    0.072492                                   (bottled beer)
..        ...                                              ...
105  0.022977                         (tropical fruit, yogurt)
106  0.033981                 (whole milk, whipped/sour cream)
107  0.055987                             (whole milk, yogurt)
108  0.022977  (root vegetables, other vegetables, whole milk)
109  0.022977           (whole milk, other vegetables, yogurt)

[110 rows x 2 columns]

In [22]:
df_combo = baskets_sets.astype(bool)

frequent_itemsets = apriori(df_combo, min_support=0.002, use_colnames=True)
frequent_itemsets['length'] = frequent_itemsets['itemsets'].apply(lambda x: len(x))

frequent_itemsets

       support                                           itemsets  length
0     0.007120                            (Instant food products)       1
1     0.028155                                         (UHT-milk)       1
2     0.002913                                 (abrasive cleaner)       1
3     0.003560                                 (artif. sweetener)       1
4     0.014887                                    (baking powder)       1
...        ...                                                ...     ...
2313  0.002265  (root vegetables, yogurt, whole milk, citrus f...       5
2314  0.002589  (yogurt, whole milk, citrus fruit, whipped/sou...       5
2315  0.002265  (yogurt, whole milk, whipped/sour cream, other...       5
2316  0.002265  (root vegetables, yogurt, whole milk, tropical...       5
2317  0.002265  (yogurt, whole milk, tropical fruit, whipped/s...       5

[2318 rows x 3 columns]

In [23]:
frequent_itemsets[(frequent_itemsets['length'] >= 3)]

       support                                           itemsets  length
1260  0.002589        (other vegetables, bottled water, UHT-milk)       3
1261  0.002265                    (soda, bottled water, UHT-milk)       3
1262  0.002589      (whole milk, other vegetables, baking powder)       3
1263  0.002265    (whole milk, baking powder, whipped/sour cream)       3
1264  0.002589                        (beef, whole milk, berries)       3
...        ...                                                ...     ...
2313  0.002265  (root vegetables, yogurt, whole milk, citrus f...       5
2314  0.002589  (yogurt, whole milk, citrus fruit, whipped/sou...       5
2315  0.002265  (yogurt, whole milk, whipped/sour cream, other...       5
2316  0.002265  (root vegetables, yogurt, whole milk, tropical...       5
2317  0.002265  (yogurt, whole milk, tropical fruit, whipped/s...       5

[1058 rows x 3 columns]

In [24]:
rules = association_rules(frequent_itemsets, metric='confidence', min_threshold=0.9)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,"(hamburger meat, curd)",(whole milk),0.003236,0.256634,0.003236,1.000000,3.896595,1.0,0.002406,inf,0.745779,0.012610,1.000000,0.506305
1,"(root vegetables, frozen fish)",(whole milk),0.002265,0.256634,0.002265,1.000000,3.896595,1.0,0.001684,inf,0.745054,0.008827,1.000000,0.504414
2,"(sausage, soda, bottled water)",(yogurt),0.003560,0.136893,0.003236,0.909091,6.640877,1.0,0.002749,9.494175,0.852452,0.023585,0.894672,0.466366
3,"(sausage, bottled water, yogurt)",(soda),0.003560,0.159223,0.003236,0.909091,5.709534,1.0,0.002669,9.248544,0.827801,0.020284,0.891875,0.464708
4,"(whole milk, butter, pip fruit)",(other vegetables),0.003560,0.192557,0.003236,0.909091,4.721161,1.0,0.002551,8.881877,0.791004,0.016779,0.887411,0.462949

In [25]:
rules = association_rules(frequent_itemsets, metric='lift', min_threshold=1)
rules.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(other vegetables),(Instant food products),0.192557,0.007120,0.002265,0.011765,1.652406,1.0,0.000894,1.004700,0.488978,0.011475,0.004678,0.164973
1,(Instant food products),(other vegetables),0.007120,0.192557,0.002265,0.318182,1.652406,1.0,0.000894,1.184250,0.397653,0.011475,0.155584,0.164973
2,(root vegetables),(Instant food products),0.110032,0.007120,0.002265,0.020588,2.891711,1.0,0.001482,1.013752,0.735065,0.019718,0.013565,0.169385
3,(Instant food products),(root vegetables),0.007120,0.110032,0.002265,0.318182,2.891711,1.0,0.001482,1.305286,0.658875,0.019718,0.233884,0.169385
4,(bottled water),(UHT-milk),0.111974,0.028155,0.006472,0.057803,2.053020,1.0,0.003320,1.031467,0.577587,0.048426,0.030507,0.143844

In [26]:
rules[(rules['lift'] >= 5) & (rules['confidence'] >= 0.8)]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
7110,"(sausage, soda, bottled water)",(yogurt),0.003560,0.136893,0.003236,0.909091,6.640877,1.0,0.002749,9.494175,0.852452,0.023585,0.894672,0.466366
7112,"(sausage, bottled water, yogurt)",(soda),0.003560,0.159223,0.003236,0.909091,5.709534,1.0,0.002669,9.248544,0.827801,0.020284,0.891875,0.464708
7378,"(rolls/buns, canned beer, sausage)",(shopping bags),0.002589,0.082848,0.002265,0.875000,10.561523,1.0,0.002051,7.337217,0.907667,0.027237,0.863709,0.451172
8130,"(other vegetables, dessert, whipped/sour cream)",(yogurt),0.002913,0.136893,0.002589,0.888889,6.493302,1.0,0.002190,7.767961,0.848466,0.018868,0.871266,0.453901
8189,"(pastry, frankfurter, other vegetables)",(rolls/buns),0.002265,0.194498,0.002265,1.000000,5.141431,1.0,0.001825,inf,0.807331,0.011647,1.000000,0.505824
8313,"(whole milk, hamburger meat, pork)",(other vegetables),0.002589,0.192557,0.002589,1.000000,5.193277,1.0,0.002090,inf,0.809539,0.013445,1.000000,0.506723